// Code generated by go-swagger; DO NOT EDIT.

package models

/**
 * Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ComplianceStatus Pass/fail compliance status
// swagger:model complianceStatus
type ComplianceStatus string

const (

	// ComplianceStatusERROR captures enum value "ERROR"
	ComplianceStatusERROR ComplianceStatus = "ERROR"

	// ComplianceStatusFAIL captures enum value "FAIL"
	ComplianceStatusFAIL ComplianceStatus = "FAIL"

	// ComplianceStatusPASS captures enum value "PASS"
	ComplianceStatusPASS ComplianceStatus = "PASS"
)

// for schema
var complianceStatusEnum []interface{}

func init() {
	var res []ComplianceStatus
	if err := json.Unmarshal([]byte(`["ERROR","FAIL","PASS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		complianceStatusEnum = append(complianceStatusEnum, v)
	}
}

func (m ComplianceStatus) validateComplianceStatusEnum(path, location string, value ComplianceStatus) error {
	if err := validate.Enum(path, location, value, complianceStatusEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this compliance status
func (m ComplianceStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateComplianceStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
