// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/resources/models"
)

// DeleteResourcesReader is a Reader for the DeleteResources structure.
type DeleteResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteResourcesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteResourcesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteResourcesOK creates a DeleteResourcesOK with default headers values
func NewDeleteResourcesOK() *DeleteResourcesOK {
	return &DeleteResourcesOK{}
}

/*DeleteResourcesOK handles this case with default header values.

OK
*/
type DeleteResourcesOK struct {
}

func (o *DeleteResourcesOK) Error() string {
	return fmt.Sprintf("[POST /delete][%d] deleteResourcesOK ", 200)
}

func (o *DeleteResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteResourcesBadRequest creates a DeleteResourcesBadRequest with default headers values
func NewDeleteResourcesBadRequest() *DeleteResourcesBadRequest {
	return &DeleteResourcesBadRequest{}
}

/*DeleteResourcesBadRequest handles this case with default header values.

Bad request
*/
type DeleteResourcesBadRequest struct {
	Payload *models.Error
}

func (o *DeleteResourcesBadRequest) Error() string {
	return fmt.Sprintf("[POST /delete][%d] deleteResourcesBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteResourcesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteResourcesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteResourcesInternalServerError creates a DeleteResourcesInternalServerError with default headers values
func NewDeleteResourcesInternalServerError() *DeleteResourcesInternalServerError {
	return &DeleteResourcesInternalServerError{}
}

/*DeleteResourcesInternalServerError handles this case with default header values.

Internal server error
*/
type DeleteResourcesInternalServerError struct {
}

func (o *DeleteResourcesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /delete][%d] deleteResourcesInternalServerError ", 500)
}

func (o *DeleteResourcesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
