// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
)

// NewDescribeOrgParams creates a new DescribeOrgParams object
// with the default values initialized.
func NewDescribeOrgParams() *DescribeOrgParams {
	var ()
	return &DescribeOrgParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeOrgParamsWithTimeout creates a new DescribeOrgParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribeOrgParamsWithTimeout(timeout time.Duration) *DescribeOrgParams {
	var ()
	return &DescribeOrgParams{

		timeout: timeout,
	}
}

// NewDescribeOrgParamsWithContext creates a new DescribeOrgParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribeOrgParamsWithContext(ctx context.Context) *DescribeOrgParams {
	var ()
	return &DescribeOrgParams{

		Context: ctx,
	}
}

// NewDescribeOrgParamsWithHTTPClient creates a new DescribeOrgParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribeOrgParamsWithHTTPClient(client *http.Client) *DescribeOrgParams {
	var ()
	return &DescribeOrgParams{
		HTTPClient: client,
	}
}

/*DescribeOrgParams contains all the parameters to send to the API endpoint
for the describe org operation typically these are written to a http.Request
*/
type DescribeOrgParams struct {

	/*Type
	  Which type of information is returned

	*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe org params
func (o *DescribeOrgParams) WithTimeout(timeout time.Duration) *DescribeOrgParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe org params
func (o *DescribeOrgParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe org params
func (o *DescribeOrgParams) WithContext(ctx context.Context) *DescribeOrgParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe org params
func (o *DescribeOrgParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe org params
func (o *DescribeOrgParams) WithHTTPClient(client *http.Client) *DescribeOrgParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe org params
func (o *DescribeOrgParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithType adds the typeVar to the describe org params
func (o *DescribeOrgParams) WithType(typeVar string) *DescribeOrgParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the describe org params
func (o *DescribeOrgParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeOrgParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param type
	qrType := o.Type
	qType := qrType
	if qType != "" {
		if err := r.SetQueryParam("type", qType); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
