// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/compliance/models"
)

// SetStatusReader is a Reader for the SetStatus structure.
type SetStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewSetStatusCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetStatusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSetStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetStatusCreated creates a SetStatusCreated with default headers values
func NewSetStatusCreated() *SetStatusCreated {
	return &SetStatusCreated{}
}

/*SetStatusCreated handles this case with default header values.

OK
*/
type SetStatusCreated struct {
}

func (o *SetStatusCreated) Error() string {
	return fmt.Sprintf("[POST /status][%d] setStatusCreated ", 201)
}

func (o *SetStatusCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetStatusBadRequest creates a SetStatusBadRequest with default headers values
func NewSetStatusBadRequest() *SetStatusBadRequest {
	return &SetStatusBadRequest{}
}

/*SetStatusBadRequest handles this case with default header values.

Bad request
*/
type SetStatusBadRequest struct {
	Payload *models.Error
}

func (o *SetStatusBadRequest) Error() string {
	return fmt.Sprintf("[POST /status][%d] setStatusBadRequest  %+v", 400, o.Payload)
}

func (o *SetStatusBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetStatusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetStatusInternalServerError creates a SetStatusInternalServerError with default headers values
func NewSetStatusInternalServerError() *SetStatusInternalServerError {
	return &SetStatusInternalServerError{}
}

/*SetStatusInternalServerError handles this case with default header values.

Internal server error
*/
type SetStatusInternalServerError struct {
}

func (o *SetStatusInternalServerError) Error() string {
	return fmt.Sprintf("[POST /status][%d] setStatusInternalServerError ", 500)
}

func (o *SetStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
