// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/remediation/models"
)

// ListRemediationsReader is a Reader for the ListRemediations structure.
type ListRemediationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListRemediationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListRemediationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListRemediationsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListRemediationsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListRemediationsOK creates a ListRemediationsOK with default headers values
func NewListRemediationsOK() *ListRemediationsOK {
	return &ListRemediationsOK{}
}

/*ListRemediationsOK handles this case with default header values.

OK
*/
type ListRemediationsOK struct {
	Payload models.Remediations
}

func (o *ListRemediationsOK) Error() string {
	return fmt.Sprintf("[GET /][%d] listRemediationsOK  %+v", 200, o.Payload)
}

func (o *ListRemediationsOK) GetPayload() models.Remediations {
	return o.Payload
}

func (o *ListRemediationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRemediationsBadRequest creates a ListRemediationsBadRequest with default headers values
func NewListRemediationsBadRequest() *ListRemediationsBadRequest {
	return &ListRemediationsBadRequest{}
}

/*ListRemediationsBadRequest handles this case with default header values.

Bad request
*/
type ListRemediationsBadRequest struct {
	Payload *models.Error
}

func (o *ListRemediationsBadRequest) Error() string {
	return fmt.Sprintf("[GET /][%d] listRemediationsBadRequest  %+v", 400, o.Payload)
}

func (o *ListRemediationsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListRemediationsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRemediationsInternalServerError creates a ListRemediationsInternalServerError with default headers values
func NewListRemediationsInternalServerError() *ListRemediationsInternalServerError {
	return &ListRemediationsInternalServerError{}
}

/*ListRemediationsInternalServerError handles this case with default header values.

Internal server error
*/
type ListRemediationsInternalServerError struct {
}

func (o *ListRemediationsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /][%d] listRemediationsInternalServerError ", 500)
}

func (o *ListRemediationsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
