// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
)

// NewListRemediationsParams creates a new ListRemediationsParams object
// with the default values initialized.
func NewListRemediationsParams() *ListRemediationsParams {

	return &ListRemediationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListRemediationsParamsWithTimeout creates a new ListRemediationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListRemediationsParamsWithTimeout(timeout time.Duration) *ListRemediationsParams {

	return &ListRemediationsParams{

		timeout: timeout,
	}
}

// NewListRemediationsParamsWithContext creates a new ListRemediationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListRemediationsParamsWithContext(ctx context.Context) *ListRemediationsParams {

	return &ListRemediationsParams{

		Context: ctx,
	}
}

// NewListRemediationsParamsWithHTTPClient creates a new ListRemediationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListRemediationsParamsWithHTTPClient(client *http.Client) *ListRemediationsParams {

	return &ListRemediationsParams{
		HTTPClient: client,
	}
}

/*ListRemediationsParams contains all the parameters to send to the API endpoint
for the list remediations operation typically these are written to a http.Request
*/
type ListRemediationsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list remediations params
func (o *ListRemediationsParams) WithTimeout(timeout time.Duration) *ListRemediationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list remediations params
func (o *ListRemediationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list remediations params
func (o *ListRemediationsParams) WithContext(ctx context.Context) *ListRemediationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list remediations params
func (o *ListRemediationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list remediations params
func (o *ListRemediationsParams) WithHTTPClient(client *http.Client) *ListRemediationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list remediations params
func (o *ListRemediationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListRemediationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
