// Code generated by go-swagger; DO NOT EDIT.

package models

/**
 * Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Paging paging
// swagger:model Paging
type Paging struct {

	// this page
	// Required: true
	// Minimum: 1
	ThisPage *int64 `json:"thisPage"`

	// total items
	// Required: true
	// Minimum: 1
	TotalItems *int64 `json:"totalItems"`

	// total pages
	// Required: true
	// Minimum: 1
	TotalPages *int64 `json:"totalPages"`
}

// Validate validates this paging
func (m *Paging) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateThisPage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalItems(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalPages(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Paging) validateThisPage(formats strfmt.Registry) error {

	if err := validate.Required("thisPage", "body", m.ThisPage); err != nil {
		return err
	}

	if err := validate.MinimumInt("thisPage", "body", int64(*m.ThisPage), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *Paging) validateTotalItems(formats strfmt.Registry) error {

	if err := validate.Required("totalItems", "body", m.TotalItems); err != nil {
		return err
	}

	if err := validate.MinimumInt("totalItems", "body", int64(*m.TotalItems), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *Paging) validateTotalPages(formats strfmt.Registry) error {

	if err := validate.Required("totalPages", "body", m.TotalPages); err != nil {
		return err
	}

	if err := validate.MinimumInt("totalPages", "body", int64(*m.TotalPages), 1, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Paging) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Paging) UnmarshalBinary(b []byte) error {
	var res Paging
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
