# Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

swagger: '2.0'
info:
  version: '1.0.0'
  title: panther-remediation-api
  description: API to invoke remediations
  contact:
    name: Panther Labs
    url: https://runpanther.io/about
    email: support@runpanther.io

schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

# The name of the CloudFormation resource for the Lambda handler function
x-panther-lambda-cfn-resource: ApiFunction

paths:
  /:
    get:
      operationId: ListRemediations
      summary: Retrieve available remediations
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Remediations'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error

  /remediate:
    post:
      operationId: RemediateResource
      summary: Synchronously remediate resource for an account.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/RemediateResource'
      responses:
        200:
          description: OK
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error

  /remediateasync:
    post:
      operationId: RemediateResourceAsync
      summary: Asynchronously remediate resource for an account.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/RemediateResource'
      responses:
        200:
          description: OK
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error

definitions:
  RemediateResource:
    type: object
    properties:
      policyId:
        $ref: '#/definitions/PolicyId'
      resourceId:
        $ref: '#/definitions/ResourceId'
    required:
      - policyId
      - resourceId

  Remediations:
    type: object
    additionalProperties:
      type: object

  ##### object properties #####
  PolicyId:
    description: A unique policy ID
    type: string
    minLength: 1
    maxLength: 200

  ResourceId:
    description: Unique resource identifier
    type: string
    minLength: 1
    maxLength: 5000

  Error:
    type: object
    properties:
      message:
        description: Error message
        type: string
    required:
      - message
