# Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Runs rules on incoming events

Parameters:
  CloudWatchLogRetentionDays:
    Type: Number
    Description: CloudWatch log retention period
    Default: 365
  Debug:
    Type: String
    Description: Toggle debug logging
    Default: false
    AllowedValues: [true, false]
  LayerVersionArns:
    Type: CommaDelimitedList
    Description: List of base LayerVersion ARNs to attach to every Lambda function
    Default: ''
  TracingMode:
    Type: String
    Description: Enable XRay tracing on Lambda and API Gateway
    AllowedValues: ['', Active, PassThrough]
    Default: ''

  MemorySizeMB:
    Type: Number
    Description: Memory (MB) available for the API Lambda handler
    Default: 512
    MinValue: 128
    MaxValue: 3008
  TimeoutSec:
    Type: Number
    Description: Timeout (seconds) for the API Lambda handler
    Default: 120
    MinValue: 5
    MaxValue: 900

  AnalysisApiId:
    Type: String
    Description: API Gateway for analysis-api
  PythonLayerArn:
    Type: String
    Description: S3 key for the Python analysis layer
  SnsTopicArn:
    Type: String
    Description: The ARN of the SNS topic
  SQSKeyId:
    Type: String
    Description: KMS key ID for SQS encryption
  ProcessedDataBucket:
    Type: String
    Description: S3 bucket for storing processed logs
  AlertsQueue:
    Type: String
    Description: The queue to forward alerts
    Default: panther-log-alert-notifications-queue

Conditions:
  AttachBaseLayers: !Not [!Equals [!Join ['', !Ref LayerVersionArns], '']]
  TracingEnabled: !Not [!Equals ['', !Ref TracingMode]]

Resources:
  SnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt Queue.Arn
      Region: !Ref AWS::Region
      TopicArn: !Ref SnsTopicArn
      RawMessageDelivery: true

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref Queue
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: sqs:SendMessage
            Resource: '*'
            Condition:
              ArnLike:
                aws:SourceArn: !Ref SnsTopicArn

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: panther-rules-engine
      KmsMasterKeyId: !Ref SQSKeyId
      # Reference on KeyReuse: https://amzn.to/2ngIsFB
      KmsDataKeyReusePeriodSeconds: 3600 # 1 hour
      VisibilityTimeout: !Ref TimeoutSec
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt [DeadLetterQueue, Arn]
        maxReceiveCount: 10

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: panther-rules-engine-dlq
      MessageRetentionPeriod: 1209600 # Max duration - 14 days
      VisibilityTimeout: !Ref TimeoutSec

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/panther-rules-engine
      RetentionInDays: !Ref CloudWatchLogRetentionDays

  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../internal/log_analysis/rules_engine
      Description: Python Rules Engine
      FunctionName: panther-rules-engine
      Handler: src.main.lambda_handler
      Environment:
        Variables:
          ANALYSIS_API_FQDN: !Sub '${AnalysisApiId}.execute-api.${AWS::Region}.amazonaws.com'
          ANALYSIS_API_PATH: v1
          DEBUG: !Ref Debug
          ALERTS_QUEUE: !Ref AlertsQueue
      MemorySize: !Ref MemorySizeMB
      Events:
        Queue:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue.Arn
            BatchSize: 10
      Layers: !If
        - AttachBaseLayers
        - !Split
          # CFN doesn't have list append, so convert to/from CSV string to prepend base layers
          - ","
          - !Sub
            - "${base},${pip}"
            - {base: !Join [",", !Ref LayerVersionArns], pip: !Ref PythonLayerArn}
        - [!Ref PythonLayerArn]
      Runtime: python3.7
      Timeout: !Ref TimeoutSec
      Tracing: !If [TracingEnabled, !Ref TracingMode, !Ref 'AWS::NoValue']
      Policies:
        - !If [TracingEnabled, 'arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess', !Ref 'AWS::NoValue']
        - Id: ReceiveFromInputSqsQueue
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:ReceiveMessage
              Resource: !GetAtt Queue.Arn
        - Id: SendToSqsQueue
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:GetQueueUrl
                - sqs:SendMessage
                - sqs:SendMessageBatch
              Resource: !Sub arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${AlertsQueue}
        - Id: ReadFromS3
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource: !Sub arn:${AWS::Partition}:s3:::${ProcessedDataBucket}/*
        - Id: AccessKms
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:Encrypt
                - kms:GenerateDataKey
              Resource: !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${SQSKeyId}
        - Id: InvokeGatewayApi
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: execute-api:Invoke
              Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AnalysisApiId}/v1/GET/enabled


